#!/bin/bash
user=${1}
while [[ ! $user ]]; do
    echo
    echo >&2 "Please enter a condor user identifier to delete: "
    read -r user
done

echo
condor_qusers "$user" -edit UserName=undefined
echo
